import 'package:flutter/material.dart';

class CustomTheme {
  static TextTheme customTextTheme = TextTheme(
    titleLarge: TextStyle(
      fontSize: 18,
      fontWeight: FontWeight.w600,
    ),
    titleMedium: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w600,
    ),
    titleSmall: TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w600,
    ),
    bodyLarge: TextStyle(
      fontSize: 18,
      fontWeight: FontWeight.w300,
    ),
    bodyMedium: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w300,
    ),
    bodySmall: TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w300,
    ),
  );

  static final elevatedButtonLightTheme = ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      backgroundColor: Colors.black,
      elevation: 0,
      foregroundColor: Colors.white,
      textStyle: customTextTheme.bodyMedium,
      minimumSize: Size(double.infinity, 46),
    ),
  );

  static final elevatedButtonDarkTheme = ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      backgroundColor: Colors.white,
      elevation: 0,
      foregroundColor: Colors.black,
      textStyle: customTextTheme.bodyMedium,
      minimumSize: Size(double.infinity, 46),
    ),
  );

  static final appBarTheme = AppBarTheme(
    scrolledUnderElevation: 0,
    backgroundColor: Colors.transparent,
  );

  static final lightTheme = ThemeData(
      useMaterial3: true,
      textTheme: customTextTheme,
      elevatedButtonTheme: elevatedButtonLightTheme,
      appBarTheme: appBarTheme,
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: const Color.fromRGBO(0, 148, 230, 1),
        surfaceTint: Color(0xff30628c),
        onPrimary: Color(0xffffffff),
        primaryContainer: Color(0xffcee5ff),
        onPrimaryContainer: Color(0xff001d33),
        secondary: Color(0xff51606f),
        onSecondary: Color(0xffffffff),
        secondaryContainer: Color(0xffd5e4f7),
        onSecondaryContainer: Color(0xff0e1d2a),
        tertiary: Color(0xff68587a),
        onTertiary: Color(0xffffffff),
        tertiaryContainer: Color(0xffefdbff),
        onTertiaryContainer: Color(0xff231533),
        error: Color(0xffba1a1a),
        onError: Color(0xffffffff),
        errorContainer: Color(0xffffdad6),
        onErrorContainer: Color(0xff410002),
        surface: Color(0xfff7f9ff),
        onSurface: Color(0xff181c20),
        onSurfaceVariant: Color(0xff42474e),
        outline: Color(0xff72777f),
        outlineVariant: Color(0xffc2c7cf),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xff2d3135),
        inversePrimary: Color(0xff9ccbfb),
        primaryFixed: Color(0xffcee5ff),
        onPrimaryFixed: Color(0xff001d33),
        primaryFixedDim: Color(0xff9ccbfb),
        onPrimaryFixedVariant: Color(0xff0f4a73),
        secondaryFixed: Color(0xffd5e4f7),
        onSecondaryFixed: Color(0xff0e1d2a),
        secondaryFixedDim: Color(0xffb9c8da),
        onSecondaryFixedVariant: Color(0xff3a4857),
        tertiaryFixed: Color(0xffefdbff),
        onTertiaryFixed: Color(0xff231533),
        tertiaryFixedDim: Color(0xffd3bfe6),
        onTertiaryFixedVariant: Color(0xff504061),
        surfaceDim: Color(0xffd8dae0),
        surfaceBright: Color(0xfff7f9ff),
        surfaceContainerLowest: Color(0xffffffff),
        surfaceContainerLow: Color(0xfff1f3f9),
        surfaceContainer: Color(0xffeceef3),
        surfaceContainerHigh: Color(0xffe6e8ee),
        surfaceContainerHighest: Color(0xffe0e2e8),
      ));

  static final darkTheme = ThemeData(
      useMaterial3: true,
      textTheme: customTextTheme,
      elevatedButtonTheme: elevatedButtonDarkTheme,
      appBarTheme: appBarTheme,
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: const Color.fromRGBO(0, 148, 230, 1),
        surfaceTint: Color(0xff9ccbfb),
        onPrimary: Color(0xff003354),
        primaryContainer: Color(0xff0f4a73),
        onPrimaryContainer: Color(0xffcee5ff),
        secondary: Color(0xffb9c8da),
        onSecondary: Color(0xff243240),
        secondaryContainer: Color(0xff3a4857),
        onSecondaryContainer: Color(0xffd5e4f7),
        tertiary: Color(0xffd3bfe6),
        onTertiary: Color(0xff392a49),
        tertiaryContainer: Color(0xff504061),
        onTertiaryContainer: Color(0xffefdbff),
        error: Color(0xffffb4ab),
        onError: Color(0xff690005),
        errorContainer: Color(0xff93000a),
        onErrorContainer: Color(0xffffdad6),
        surface: Color(0xff101418),
        onSurface: Color(0xffe0e2e8),
        onSurfaceVariant: Color(0xffc2c7cf),
        outline: Color(0xff8c9199),
        outlineVariant: Color(0xff42474e),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xffe0e2e8),
        inversePrimary: Color(0xff30628c),
        primaryFixed: Color(0xffcee5ff),
        onPrimaryFixed: Color(0xff001d33),
        primaryFixedDim: Color(0xff9ccbfb),
        onPrimaryFixedVariant: Color(0xff0f4a73),
        secondaryFixed: Color(0xffd5e4f7),
        onSecondaryFixed: Color(0xff0e1d2a),
        secondaryFixedDim: Color(0xffb9c8da),
        onSecondaryFixedVariant: Color(0xff3a4857),
        tertiaryFixed: Color(0xffefdbff),
        onTertiaryFixed: Color(0xff231533),
        tertiaryFixedDim: Color(0xffd3bfe6),
        onTertiaryFixedVariant: Color(0xff504061),
        surfaceDim: Color(0xff101418),
        surfaceBright: Color(0xff36393e),
        surfaceContainerLowest: Color(0xff0b0f12),
        surfaceContainerLow: Color(0xff181c20),
        surfaceContainer: Color(0xff1c2024),
        surfaceContainerHigh: Color(0xff272a2f),
        surfaceContainerHighest: Color(0xff323539),
      ));
}
